[package]
name = "aros"
version = "0.1.0"
authors = ["k0pernicus <antonin.carette@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1"
vga = { path = "src/vga" }

[profile.release]
panic = "abort"
