[package]
name = "aros"
version = "0.1.0"
authors = ["k0pernicus <antonin.carette@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
x86_64 = "0.11"
vga = { path = "src/vga" }
interrupts = { path = "src/interrupts" }

[profile.release]
panic = "abort"
